# WorldGuardExtraFlagsPlus Configuration
# This file is located in the WorldGuard plugin folder
# You can customize plugin behavior here
#
# IMPORTANT: This file is reloaded when you use /wg reload or /wgefp reload

permit-workbenches:
  # If true, blocks placement of workbench blocks in regions with permit-workbenches flag
  # Default: false
  permit-workbench-block-placement-too: false
  
  # If true, "ALL" keyword in permit-workbenches flag will also include ender chests
  # Default: false (ALL does not include ender chests by default)
  permit-all-includes-enderchest: false

godmode:
  auto-give-godmode-region-left: false